version: '3.8'

services:
  hexsatisfaction:
    build: ./
    command: ./wait-for-postgres.sh db go run main.go
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=18051965q
  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=18051965q
    ports:
      - 5432:5432




