http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

grpc:
  host: localhost
  port: 8080

pg:
  databaseName: postgres
  databaseSslMode: disable
  databaseDialect: postgres


