basePath: /
definitions:
  middleware.SwagEmptyError:
    type: object
  middleware.SwagError:
    properties:
      message:
        type: string
    type: object
  model.Author:
    properties:
      age:
        type: integer
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      userID:
        type: integer
    type: object
  model.CreateAuthorRequest:
    properties:
      age:
        description: 'required: true'
        type: integer
      description:
        description: 'required: true'
        type: string
      name:
        description: 'required: true'
        type: string
      userID:
        description: 'required: true'
        type: integer
    type: object
  model.LoginUserRequest:
    properties:
      login:
        description: 'required: true'
        type: string
      password:
        description: 'required: true'
        type: string
    type: object
  model.RegisterUserRequest:
    properties:
      login:
        description: 'required: true'
        type: string
      password:
        description: 'required: true'
        type: string
    type: object
  model.UpdateAuthorRequest:
    properties:
      age:
        description: 'required: true'
        type: integer
      description:
        description: 'required: true'
        type: string
      name:
        description: 'required: true'
        type: string
      userID:
        description: 'required: true'
        type: integer
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Service for Hexsatisfaction
  title: Hexsatisfaction API
  version: "1.0"
paths:
  /author/:
    get:
      consumes:
      - application/json
      description: Find authors
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Author'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: No authors
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      summary: FindAll
      tags:
      - author
  /author/{name}:
    get:
      consumes:
      - application/json
      description: Find authors by name
      parameters:
      - description: Author name
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Author'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: No authors
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      summary: FindByName
      tags:
      - author
  /author/api/:
    post:
      consumes:
      - application/json
      description: Create author
      parameters:
      - description: Author
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/model.CreateAuthorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - author
  /author/api/{id}:
    delete:
      consumes:
      - application/json
      description: Delete author
      parameters:
      - description: Author id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: No author
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      security:
      - ApiKeyAuth: []
      summary: Delete
      tags:
      - author
    get:
      consumes:
      - application/json
      description: Find author by id
      parameters:
      - description: Author id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Author'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: No author
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      security:
      - ApiKeyAuth: []
      summary: FindByID
      tags:
      - author
    put:
      consumes:
      - application/json
      description: Update author
      parameters:
      - description: Author id
        in: path
        name: id
        required: true
        type: integer
      - description: Author
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/model.UpdateAuthorRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: No author
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - author
  /author/api/user/{id}:
    get:
      consumes:
      - application/json
      description: Find author by user id
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Author'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: No author
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      security:
      - ApiKeyAuth: []
      summary: FindByUserID
      tags:
      - author
  /user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: User credentials
        in: body
        name: userCred
        required: true
        schema:
          $ref: '#/definitions/model.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/middleware.SwagEmptyError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      summary: SingIn
      tags:
      - user
  /user/registration:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: User credentials
        in: body
        name: userCred
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "302":
          description: Found
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/middleware.SwagError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middleware.SwagError'
      summary: SingUp
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
